// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMBJiPUirocA0E8duC1KCPqnRGQTLnUjk',
    appId: '1:842851685305:web:7055dc4ac27aaaf71f1c68',
    messagingSenderId: '842851685305',
    projectId: 'pulse-news-a1e1a',
    authDomain: 'pulse-news-a1e1a.firebaseapp.com',
    storageBucket: 'pulse-news-a1e1a.firebasestorage.app',
    measurementId: 'G-EL2GMZRH88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzekXE_VpFB8qlZEaUrdnSMiTNvDXG8Jk',
    appId: '1:842851685305:android:d273c6892d63c54b1f1c68',
    messagingSenderId: '842851685305',
    projectId: 'pulse-news-a1e1a',
    storageBucket: 'pulse-news-a1e1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnImddmiaJ-EIxtzFg52R_DMj7oUkheUs',
    appId: '1:842851685305:ios:3703cee51608d8981f1c68',
    messagingSenderId: '842851685305',
    projectId: 'pulse-news-a1e1a',
    storageBucket: 'pulse-news-a1e1a.firebasestorage.app',
    iosBundleId: 'com.example.pulsenews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnImddmiaJ-EIxtzFg52R_DMj7oUkheUs',
    appId: '1:842851685305:ios:3703cee51608d8981f1c68',
    messagingSenderId: '842851685305',
    projectId: 'pulse-news-a1e1a',
    storageBucket: 'pulse-news-a1e1a.firebasestorage.app',
    iosBundleId: 'com.example.pulsenews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMBJiPUirocA0E8duC1KCPqnRGQTLnUjk',
    appId: '1:842851685305:web:6a1dc03f649d05851f1c68',
    messagingSenderId: '842851685305',
    projectId: 'pulse-news-a1e1a',
    authDomain: 'pulse-news-a1e1a.firebaseapp.com',
    storageBucket: 'pulse-news-a1e1a.firebasestorage.app',
    measurementId: 'G-H0C87CCHFE',
  );
}
